import { Geist, Geist_Mono } from 'next/font/google';
import { Noto_Sans } from 'next/font/google';
import './globals.css';
import NavBar from '../components/NavBar';
import { ThemeProvider } from '../components/theme-provider';

const notoSans = Noto_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
});
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${notoSans.className} antialiased min-h-screen px-4 lg:px-6 bg-linear-to-b from-[hsl(215,74%,95%)] to-[hsl(185,48%,95%)] dark:bg-linear-to-b dark:from-[#040816] dark:to-[#09153e]`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className=" max-w-7xl mx-auto mt-8 mb-14">
            <NavBar />
          </header>
          <main className=" max-w-7xl mx-auto mb-8">{children}</main>
        </ThemeProvider>
      </body>
    </html>
  );
}
